name = "xenglish-api"
main = "src/index.ts"
compatibility_date = "2026-02-07"
workers_dev = true
preview_urls = false

[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimitDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RateLimitDurableObject"]
